# abook
# Autogenerated from man page /usr/share/man/man1/abook.1.gz
complete -c abook -s h -l help --description 'Show usage.'
complete -c abook -s C -l config --description 'Use an alternative configuration file (default is $HOME/. abook/abookrc).'
complete -c abook -l datafile --description 'Use an alternative addressbook file (default is $HOME/. abook/addressbook).'
complete -c abook -l mutt-query -l outformat --description 'Make a query for mutt (search the addressbook for <string>).'
complete -c abook -l convert -l informat -l infile -l outfile --description 'Converts <inputfile> in <inputformat> to <outputfile> in <outputformat> (defa…'
complete -c abook -l outformatstr --description 'Only used if --mutt-query or --convert is specified and --outformat=custom.'
complete -c abook -l add-email --description 'Read an e-mail message from stdin and add the sender to the addressbook.'
complete -c abook -l add-email-quiet --description 'Same as --add-email but doesn\'t confirm adding.'
complete -c abook -l formats --description 'List available formats.'

