# alternatives
# Autogenerated from man page /usr/share/man/man8/alternatives.8.gz
complete -c alternatives -l verbose --description 'Generate more comments about what  alternatives is doing.'
complete -c alternatives -l quiet --description 'Don\'t generate any comments unless errors occur.'
complete -c alternatives -l test --description 'Don\'t actually do anything, just say what would be done.'
complete -c alternatives -l help --description 'Give some usage information (and say which version of  alternatives this is).'
complete -c alternatives -l version --description 'Tell which version of  alternatives this is (and give some usage information).'
complete -c alternatives -l altdir --description 'Specifies the alternatives directory, when this is to be different from the d…'
complete -c alternatives -l admindir --description 'Specifies the administrative directory, when this is to be different from the…'
complete -c alternatives -l install -l slave -l initscript --description 'Add a group of alternatives to the system.'
complete -c alternatives -l remove --description 'Remove an alternative and all of its associated slave links.'
complete -c alternatives -l set --description 'The symbolic link and slaves for link group name set to those configured for …'
complete -c alternatives -l config --description 'Present the user with a configuration menu for choosing the master link and s…'
complete -c alternatives -l auto --description 'Switch the master symlink  name to automatic mode.'
complete -c alternatives -l display --description 'Display information about the link group of which name is the master link.'

