# ascii
# Autogenerated from man page /usr/share/man/man1/ascii.1.gz
complete -c ascii -s t --description 'Script-friendly mode, emits only ISO/decimal/hex/octal/binary encodings of th…'
complete -c ascii -s s --description 'Parse multiple characters.  Convenient way of parsing strings.'
complete -c ascii -s d --description 'Ascii table in decimal.'
complete -c ascii -s x --description 'Ascii table in hex.'
complete -c ascii -s o --description 'Ascii table in octal.'
complete -c ascii -s h -s '?' --description 'Show summary of options and a simple ASCII table.'
complete -c ascii -s v --description 'Show version of program.'

