# autoheader-2
# Autogenerated from man page /usr/share/man/man1/autoheader-2.69.1.gz
complete -c autoheader-2 -s h -l help --description 'print this help, then exit.'
complete -c autoheader-2 -s V -l version --description 'print version number, then exit.'
complete -c autoheader-2 -s v -l verbose --description 'verbosely report processing.'
complete -c autoheader-2 -s d -l debug --description 'don\'t remove temporary files.'
complete -c autoheader-2 -s f -l force --description 'consider all files obsolete.'
complete -c autoheader-2 -s W -l warnings --description 'report the warnings falling in CATEGORY . SS "Warning categories include:".'
complete -c autoheader-2 -s B -l prepend-include --description 'prepend directory DIR to search path.'
complete -c autoheader-2 -s I -l include --description 'append directory DIR to search path AUTHOR Written by Roland McGrath and Akim…'

