# autoconf-2
# Autogenerated from man page /usr/share/man/man1/autoconf-2.69.1.gz
complete -c autoconf-2 -s h -l help --description 'print this help, then exit.'
complete -c autoconf-2 -s V -l version --description 'print version number, then exit.'
complete -c autoconf-2 -s v -l verbose --description 'verbosely report processing.'
complete -c autoconf-2 -s d -l debug --description 'don\'t remove temporary files.'
complete -c autoconf-2 -s f -l force --description 'consider all files obsolete.'
complete -c autoconf-2 -s o -l output --description 'save output in FILE (stdout is the default).'
complete -c autoconf-2 -s W -l warnings --description 'report the warnings falling in CATEGORY [syntax] .'
complete -c autoconf-2 -s B -l prepend-include --description 'prepend directory DIR to search path.'
complete -c autoconf-2 -s I -l include --description 'append directory DIR to search path . SS "Tracing:".'
complete -c autoconf-2 -s t -l trace --description 'report the list of calls to MACRO.'
complete -c autoconf-2 -s i -l initialization --description 'also trace Autoconf\'s initialization process.'

