# autoreconf-2
# Autogenerated from man page /usr/share/man/man1/autoreconf-2.69.1.gz
complete -c autoreconf-2 -s h -l help --description 'print this help, then exit.'
complete -c autoreconf-2 -s V -l version --description 'print version number, then exit.'
complete -c autoreconf-2 -s v -l verbose --description 'verbosely report processing.'
complete -c autoreconf-2 -s d -l debug --description 'don\'t remove temporary files.'
complete -c autoreconf-2 -s f -l force --description 'consider all files obsolete.'
complete -c autoreconf-2 -s i -l install --description 'copy missing auxiliary files.'
complete -c autoreconf-2 -l no-recursive --description 'don\'t rebuild sub-packages.'
complete -c autoreconf-2 -s s -l symlink --description 'with -i, install symbolic links instead of copies.'
complete -c autoreconf-2 -s m -l make --description 'when applicable, re-run . /configure && make.'
complete -c autoreconf-2 -s W -l warnings --description 'report the warnings falling in CATEGORY [syntax] .'
complete -c autoreconf-2 -s B -l prepend-include --description 'prepend directory DIR to search path.'
complete -c autoreconf-2 -s I -l include --description 'append directory DIR to search path.'

