# bmp2png
# Autogenerated from man page /usr/share/man/man1/bmp2png.1.gz
complete -c bmp2png -s N --description 'Compression level in range 0. 9 (default is 6).'
complete -c bmp2png -s a --description 'Preserve alpha channel.'
complete -c bmp2png -s b --description 'Preserve alpha channel.'
complete -c bmp2png -s e --description 'Delete input files after successful conversion.'
complete -c bmp2png -s f --description 'Specify filter type(s) used to create \\s-1PNG\\s0 files type: none, sub, up, a…'
complete -c bmp2png -s h --description 'Display short help.'
complete -c bmp2png -s i --description 'Create interlaced \\s-1PNG\\s0 file.'
complete -c bmp2png -s l --description 'Log errors to \\f(CW\\*(C`. /p2berror. log\\*(C\' file.'
complete -c bmp2png -s o --description 'Specify name for output \\s-1FILE\\s0.'
complete -c bmp2png -s p --description 'Mark the specified color as transparent color: #RRGGBB(html hex) / \\s-1RR\\s0,…'
complete -c bmp2png -s q --description 'Quiet mode.'
complete -c bmp2png -s t --description 'Set the timestamp of input file on output file.'

