# card
# Autogenerated from man page /usr/share/man/man1/card.1.gz
complete -c card -s h -l help --description 'display this help and exit.'
complete -c card -s v -l version --description 'display version information and exit.'
complete -c card -s o -l output --description 'save the output in FILE.'
complete -c card -s l -l language --description 'print the help in the language LL (default: English).'
complete -c card -l command --description 'perform pretty-printing on the output of CMD (e. g.'

