# cdargs
# Autogenerated from man page /usr/share/man/man1/cdargs.1.gz
complete -c cdargs -s h -l help --description 'display usage information and exit.'
complete -c cdargs -s v -l version --description 'output version information and exit.'
complete -c cdargs -s a -l add --description 'add path to the bookmarks list using the optional desc as description string.'
complete -c cdargs -s f -l file --description 'uses the given FILE as bookmarks file.'
complete -c cdargs -s u -l user --description 'read the default bookmarks file of USER.  Won\'t modify that file.'
complete -c cdargs -s o -l output --description 'use FILE as the result-file (who knows what The World might make of this feat…'
complete -c cdargs -s b -l browse --description 'start  cdargs in BROWSE mode in the current directory.'
complete -c cdargs -s r -l noresolve --description 'Don\'t exit with a result when the Needle matches a description exactly (which…'
complete -c cdargs -s c -l cwd --description 'Make the current working directory the current entry on startup if it appears…'
complete -c cdargs -l nowrap --description 'Don\'t wrap the cursor around when hitting the end of the list.'

