# checkX
# Autogenerated from man page /usr/share/man/man1/checkX.1.gz
complete -c checkX -s h -l help --description 'print this help message and exit.'
complete -c checkX -s v -l version --description 'print version information and exit.'
complete -c checkX -s d -l display --description 'use STRING instead of $DISPLAY.'
complete -c checkX -s l -l location --description 'print location of Xlib DLL on stdout.'
complete -c checkX -s a -l appendpath --description 'append STRING to value of $PATH (cumulative).'
complete -c checkX -s p -l prependpath --description 'prepend STRING to value of $PATH (cumulative).'
complete -c checkX -s r -l replacepath --description 'use STRING instead of $PATH when searching.'
complete -c checkX -s x -l xlibname --description 'use exactly STRING instead of fuzzy cygX11-n. dll search.'
complete -c checkX -s t -l timeout --description 'allow FLOAT seconds to connect with Xserver defaults to 0. 5, use 0.'
complete -c checkX -l nogui --description 'disable informational popups.'
complete -c checkX -l notty --description 'disable stderr messages.'
complete -c checkX -l debug --description 'turn on debugging messages.'
complete -c checkX -l no-silent --description 'allow error, warning, and info messages.'

