# chkconfig
# Autogenerated from man page /usr/share/man/man8/chkconfig.8.gz
complete -c chkconfig -l level --description 'Specifies the run levels an operation should pertain to.'
complete -c chkconfig -l add --description 'This option adds a new service for management by chkconfig.'
complete -c chkconfig -l del --description 'The service is removed from chkconfig management, and any symbolic links in /…'
complete -c chkconfig -l list --description 'This option lists all of the services which chkconfig knows about, and whethe…'
complete -c chkconfig -l 'init.d' --description 'This option allows you to alter where chkconfig expects to find the system in…'
complete -c chkconfig -l 'rc.d' --description 'This option allows you to alter where chkconfig looks for the rc[0-9].'
complete -c chkconfig -l 'xinetd.d' --description 'This option allows you to alter where chkconfig looks for the xinetd service …'

