# clisp
# Autogenerated from man page /usr/share/man/man1/clisp.1.gz
complete -c clisp -o 'h
.br
--help' --description 'Displays a help message on how to invoke \\m[blue]CLISP\\m[]\\s-2\\u[6]\\d\\s+2.'
complete -c clisp -l version --description 'Displays the \\m[blue]CLISP\\m[]\\s-2\\u[6]\\d\\s+2 version number, as given by the…'
complete -c clisp -l license --description 'Displays a summary of the licensing information, the \\m[blue]GNU\\m[]\\s-2\\u[8]…'
complete -c clisp -o help-image --description 'Displays information about the memory image being invoked: whether is it suit…'
complete -c clisp -s B --description 'Specifies the installation directory.'
complete -c clisp -s b --description 'Print the installation directory and exit immediately.'
complete -c clisp -s M --description 'Specifies the initial memory image.'
complete -c clisp -s L --description 'Specifies the language \\m[blue]CLISP\\m[]\\s-2\\u[6]\\d\\s+2 uses to communicate w…'
complete -c clisp -s N --description 'Specifies the base directory of locale files.'
complete -c clisp -o 'q
.br
--quiet
.br
--silent
.br
-v
.br
--verbose' --description 'Change verbosity level: by default, \\m[blue]CLISP\\m[]\\s-2\\u[6]\\d\\s+2 displays…'
complete -c clisp -o repl --description 'Start an interactive \\m[blue]read-eval-print loop\\m[]\\s-2\\u[2]\\d\\s+2 after pr…'
complete -c clisp -s w --description 'Wait for a keypress after program termination.'
complete -c clisp -s I --description 'Interact better with \\m[blue]Emacs\\m[]\\s-2\\u[23]\\d\\s+2 (useful when running \\…'
complete -c clisp -o disable-readline --description 'Do not use \\m[blue]GNU\\m[]\\s-2\\u[8]\\d\\s+2 \\m[blue]readline\\m[]\\s-2\\u[26]\\d\\s+…'
complete -c clisp -o ansi --description 'Comply with the [ANSI CL standard] specification even where \\m[blue]CLISP\\m[]…'
complete -c clisp -o traditional --description 'Traditional: reverses the residual effects of -ansi in the saved memory image.'
complete -c clisp -o modern --description 'Provides a modern view of symbols: at startup the \\m[blue]*PACKAGE*\\m[]\\s-2\\u…'
complete -c clisp -s p --description 'At startup the value of the variable \\m[blue]*PACKAGE*\\m[]\\s-2\\u[28]\\d\\s+2 wi…'
complete -c clisp -s C --description 'Compile when loading: at startup the value of the variable CUSTOM:*LOAD-COMPI…'
complete -c clisp -o norc --description 'Normally \\m[blue]CLISP\\m[]\\s-2\\u[6]\\d\\s+2 loads the user \\m[blue]\\(lqrun cont…'
complete -c clisp -o lp --description 'Specifies directories to be added to CUSTOM:*LOAD-PATHS* at startup.'
complete -c clisp -s i --description 'Specifies initialization files to be \\m[blue]LOAD\\m[]\\s-2\\u[31]\\d\\s+2ed at st…'
complete -c clisp -s c --description 'Compiles the specified lisp-files to bytecode (*. fas).'
complete -c clisp -s o --description 'Specifies the output file or directory for the compilation of the last specif…'
complete -c clisp -s l --description 'Produce a bytecode \\m[blue]DISASSEMBLE\\m[]\\s-2\\u[35]\\d\\s+2 listing (*.'
complete -c clisp -s x --description 'Executes a series of arbitrary expressions instead of a \\m[blue]read-eval-pri…'
complete -c clisp -s h --description '.'
complete -c clisp -l help --description '.'
complete -c clisp -s K --description '.'
complete -c clisp -s m --description '.'
complete -c clisp -o Edomain --description '.'
complete -c clisp -s q --description '.'
complete -c clisp -l quiet --description '.'
complete -c clisp -l silent --description '.'
complete -c clisp -s v --description '.'
complete -c clisp -l verbose --description '.'
complete -c clisp -o 'v.' --description '.'
complete -c clisp -o on-error --description '.'
complete -c clisp -l mJohn --description 'When m[blue]CLISPm[]\\u[6]\\d is invoked, the runtime loads the initial memory …'

