# column
# Autogenerated from man page /usr/share/man/man1/column.1.gz
complete -c column -s c -l columns --description 'Output is formatted to a width specified as number of characters.'
complete -c column -s o -l output-separator --description 'Specify the columns delimiter for table output (default is two spaces).'
complete -c column -s s -l separator --description 'Specify the possible input item delimiters (default is whitespace).'
complete -c column -s t -l table --description 'Determine the number of columns the input contains and create a table.'
complete -c column -s x -l fillrows --description 'Fill columns before filling rows.'
complete -c column -s V -l version --description 'Display version information and exit.'
complete -c column -s h -l help --description 'Display help text and exit.'

