# cygcheck
# Autogenerated from man page /usr/share/man/man1/cygcheck.1.gz
complete -c cygcheck -s c --description 'option checks the version and status of installed Cygwin packages.'
complete -c cygcheck -s v --description 'option.'
complete -c cygcheck -s d --description 'option and cygcheck will only output the name and version for each package.'
complete -c cygcheck -s s --description 'option, cygcheck will give general system information.'
complete -c cygcheck -s f --description 'option helps you to track down which package a file came from, and.'
complete -c cygcheck -s l --description 'lists all files in a package.'
complete -c cygcheck -s h --description 'option prints additional helpful messages in the report, at the beginning of …'
complete -c cygcheck -s r --description 'option causes cygcheck to search your registry for information that is releva…'
complete -c cygcheck -s p --description 'option can be used to search the entire official Cygwin package repository.'

