# cygport
# Autogenerated from man page /usr/share/man/man1/cygport.1.gz
complete -c cygport -l 32 -s 4 --description 'build package for i686 Cygwin.'
complete -c cygport -l 64 -s 8 --description 'build package for x86_64 Cygwin.'
complete -c cygport -l debug --description 'enable debugging messages .'

