# ddir
# Autogenerated from man page /usr/share/man/man1/ddir.1.gz
complete -c ddir -s d -l dir --description 'Display only directories.'
complete -c ddir -s h -l help --description 'Print text help.'
complete -c ddir -l help-exclude --description 'Print default exclude path value when --exclude-vcs is used.'
complete -c ddir -l help-html --description 'Print help in \\s-1HTML\\s0 format.'
complete -c ddir -l help-man --description 'Print help in manual page \\f(CWman(1) format.'
complete -c ddir -s i -l include --description 'Include files mathing regexp.  The match is done against whole path.'
complete -c ddir -s v -l verbose --description 'Print informational messages.'
complete -c ddir -s V -l version --description 'Print contact and version information.'
complete -c ddir -s x -l exclude --description 'Ignore files mathing regexp.  The match is done against whole path.'

