# deurlname
# Autogenerated from man page /usr/share/man/man1/deurlname.1.gz
complete -c deurlname -s v -l verbose --description 'Display every rename done.'
complete -c deurlname -l help --description 'Show summary of options.'
complete -c deurlname -l version --description 'Output version information and exit.'

