# duff
# Autogenerated from man page /usr/share/man/man1/duff.1.gz
complete -c duff -s 0 --description 'If reading file names from stdin, assume they are null-terminated, instead of…'
complete -c duff -s H --description 'Follow symbolic links listed on the command line.'
complete -c duff -s L --description 'Follow all symbolic links.  This overrides any previous H or P option.'
complete -c duff -s P --description 'Don\'t follow any symbolic links.  This overrides any previous H or L option.'
complete -c duff -s a --description 'Include hidden files and directories when searching recursively.'
complete -c duff -s d --description 'The message digest function to use.'
complete -c duff -s e --description 'Excess mode.  List all but one file from each cluster of duplicates.'
complete -c duff -s f --description 'Set the format of the cluster header.'
complete -c duff -s h --description 'Display help information and exit.'
complete -c duff -s l --description 'The minimum size of files to be sampled.'
complete -c duff -s q --description 'Quiet mode.  Suppress warnings and error messages.'
complete -c duff -s p --description 'Physical mode.  Make duff consider physical files instead of hard links.'
complete -c duff -s r --description 'Recursively search into all specified directories.'
complete -c duff -s t --description 'Thorough mode.  Distrust digests as a guarantee for equality.'
complete -c duff -s v --description 'Display version information and exit.'
complete -c duff -s z --description 'Do not consider empty files to be equal.'

