# dumper
# Autogenerated from man page /usr/share/man/man1/dumper.1.gz
complete -c dumper -s d -l verbose --description '.'
complete -c dumper -s h -l help --description '.'
complete -c dumper -s q -l quiet --description '.'
complete -c dumper -s V -l version --description 'DESCRIPTION.'

