# fdupes
# Autogenerated from man page /usr/share/man/man1/fdupes.1.gz
complete -c fdupes -s r -l recurse --description 'for every directory given follow subdirectories encountered within.'
complete -c fdupes -s R -l recurse: --description 'for each directory given after this option follow subdirectories encountered …'
complete -c fdupes -s s -l symlinks --description 'follow symlinked directories.'
complete -c fdupes -s H -l hardlinks --description 'normally, when two or more files point to the same disk area they are treated…'
complete -c fdupes -s n -l noempty --description 'exclude zero-length files from consideration.'
complete -c fdupes -s f -l omitfirst --description 'omit the first file in each set of matches.'
complete -c fdupes -s 1 -l sameline --description 'list each set of matches on a single line.'
complete -c fdupes -s S -l size --description 'show size of duplicate files.'
complete -c fdupes -s q -l quiet --description 'hide progress indicator.'
complete -c fdupes -s d -l delete --description 'prompt user for files to preserve, deleting all others (see  CAVEATS below).'
complete -c fdupes -s N -l noprompt --description 'when used together with --delete, preserve the first file in each set of dupl…'
complete -c fdupes -s v -l version --description 'display fdupes version.'
complete -c fdupes -s h -l help --description 'displays help SEE ALSO.'
complete -c fdupes -l symlink --description 'a user could accidentally preserve a symlink while deleting the file it point…'

