# fixps
# Autogenerated from man page /usr/share/man/man1/fixps.1.gz
complete -c fixps -s h -l help --description 'display this help and exit.'
complete -c fixps -s v -l version --description 'display version information and exit.'
complete -c fixps -s q -l quiet --description 'don\'t print informational messages.'
complete -c fixps -s o -l output --description 'save result in FILE.   If FILE is `-\', send to stdout.'
complete -c fixps -s f -l force --description 'force full rewrite by ghostscript.'
complete -c fixps -s n -l no-fix --description 'don\'t fix the FILE, but still honor `-o\'.'
complete -c fixps -s c -l check -l dry-run --description 'don\'t perform any action . SS "Fixes:".'

