# flip
# Autogenerated from man page /usr/share/man/man1/flip.1.gz
complete -c flip -s u --description 'Convert to **IX format (CR LF => LF, lone CR or LF unchanged, trailing contr…'
complete -c flip -s m --description 'Convert to MS-DOS format (lone LF => CR LF, lone CR unchanged).'
complete -c flip -s h --description 'Give a help message.'
complete -c flip -s v --description 'Be verbose, print filenames as they are processed.'
complete -c flip -s t --description 'Touch files (don\'t preserve timestamps).'
complete -c flip -s s --description 'Strip high bit.'
complete -c flip -s b --description 'Convert binary files too (else binary files are left unchanged).'
complete -c flip -o 'u' --description 'Convert to **IX format (CR LF => LF, lone CR or LF unchanged, trailing contr…'
complete -c flip -o 'm' --description 'Convert to MS-DOS format (lone LF => CR LF, lone CR unchanged).'
complete -c flip -o 'h' --description 'Give a help message.'
complete -c flip -o 'v' --description 'Be verbose, print filenames as they are processed.'
complete -c flip -o 't' --description 'Touch files (don\'t preserve timestamps).'
complete -c flip -o 's' --description 'Strip high bit.'
complete -c flip -o 'b' --description 'Convert binary files too (else binary files are left unchanged).'
complete -c flip -o 'z' --description 'Truncate file at first control Z encountered.'

