# ftpd
# Autogenerated from man page /usr/share/man/man8/ftpd.8.gz
complete -c ftpd -s a -l auth --description 'use AUTH for authentication.'
complete -c ftpd -s A -l anonymous-only --description 'server configured for anonymous service only.'
complete -c ftpd -s d -l debug --description 'debug mode.'
complete -c ftpd -s D -l daemon --description 'start the ftpd standalone.'
complete -c ftpd -s l -l logging --description 'increase verbosity of syslog messages.'
complete -c ftpd -s p -l pidfile --description 'change default location of pidfile.'
complete -c ftpd -s q -l no-version --description 'do not display version in banner.'
complete -c ftpd -s t -l timeout --description 'set default idle timeout.'
complete -c ftpd -s T -l max-timeout --description 'reset maximum value of timeout allowed.'
complete -c ftpd -s u -l umask --description 'set default umask P AUTH can be one of the following:.'
complete -c ftpd -s '?' -l help --description 'give this help list.'
complete -c ftpd -l usage --description 'give a short usage message.'
complete -c ftpd -s V -l version --description 'print program version.'

