# getconf
# Autogenerated from man page /usr/share/man/man1/getconf.1.gz
complete -c getconf -s v --description 'option, the parameter denotes a specification for which the value of the conf…'
complete -c getconf -s a --description 'option to print a list of all available configuration variables for the syste…'

