# gif2tiff
# Autogenerated from man page /usr/share/man/man1/gif2tiff.1.gz
complete -c gif2tiff -s c --description 'Specify a compression scheme to use when writing image data:  "-c none" for n…'
complete -c gif2tiff -s r --description 'Write data with a specified number of rows per strip; by default the number o…'

