# hexedit
# Autogenerated from man page /usr/share/man/man1/hexedit.1.gz
complete -c hexedit -s s -l sector --description 'Format the display to have entire sectors.'
complete -c hexedit -s m -l maximize --description 'Try to maximize the display.'
complete -c hexedit -s h -l help --description 'Show the usage.  COMMANDS (quickly) Moving.'

