# icp
# Autogenerated from man page /usr/share/man/man1/icp.1.gz
complete -c icp -l command --description 'Specify command to run instead of the default `mv\' or `cp\'.'
complete -c icp -l arg-options --description 'Specify what comma-separated options for mv, cp, or the command specified wit…'
complete -c icp -l pass-through --description 'Run mv/cp (or the command specified with --command) if two or more arguments …'
complete -c icp -l help --description 'Show summary of options.'
complete -c icp -l version --description 'Output version information and exit.'

