# ifnames-2
# Autogenerated from man page /usr/share/man/man1/ifnames-2.69.1.gz
complete -c ifnames-2 -s h -l help --description 'print this help, then exit.'
complete -c ifnames-2 -s V -l version --description 'print version number, then exit AUTHOR Written by David J.'

