# inetd
# Autogenerated from man page /usr/share/man/man8/inetd.8.gz
complete -c inetd -s d -l debug --description 'turn on debugging, run in foreground mode.'
complete -c inetd -l environment --description 'pass local and remote socket information in environment variables.'
complete -c inetd -s p -l pidfile --description 'override pidfile (default: "/var/run/inetd. pid").'
complete -c inetd -l resolve --description 'resolve IP addresses when setting environment variables (see --environment).'
complete -c inetd -s R -l rate --description 'maximum invocation rate (per minute) P Cygwin-specific options:.'
complete -c inetd -s D -l no-daemonize --description 'Do not run as a daemon.'
complete -c inetd -s T -l traditional-daemon --description 'This option is present for backwards compatibility.'
complete -c inetd -s '?' -l help --description 'give this help list.'
complete -c inetd -l usage --description 'give a short usage message.'
complete -c inetd -s V -l version --description 'print program version.'

