# ipcalc
# Autogenerated from man page /usr/share/man/man1/ipcalc.1.gz
complete -c ipcalc -s n --description 'Don\'t display ANSI color codes.'
complete -c ipcalc -s b --description 'Suppress the bitwise output.'
complete -c ipcalc -s c --description 'Just print bit-count-mask of given address.'
complete -c ipcalc -s h --description 'Display results as HTML.'
complete -c ipcalc -o help --description 'Longer help text.'
complete -c ipcalc -s v --description 'Print Version EXAMPLES ipcalc 192. 168. 0. 1/24.'

