# kill
# Autogenerated from man page /usr/share/man/man1/kill.1.gz
complete -c kill -s f --description 'option, the "pid" values used by kill are the Cygwin pids, not the Windows pi…'
complete -c kill -o signN --description 'option, either with a signal number or a signal name (minus the "SIG" part), …'

