# locale
# Autogenerated from man page /usr/share/man/man1/locale.1.gz
complete -c locale -s i --description '.'
complete -c locale -s u --description '.'
complete -c locale -s s --description '.'
complete -c locale -s f --description '.'
complete -c locale -s n --description 'options can be used to request the various Windows locale settings.'
complete -c locale -s U --description 'option locale appends the string ". UTF-8" to enforce using UTF-8.'
complete -c locale -s a --description 'option is helpful to learn which locales are supported by your Windows machin…'
complete -c locale -s v --description 'option prints more detailed information about each available locale.'
complete -c locale -l ----------------------------------------------------------------------------- --description ' language | Afrikaans territory | South Africa   codeset | ISO-8859-1.'
complete -c locale -s m --description 'option prints the names of the available charmaps supported by Cygwin to stdo…'
complete -c locale -s c --description 'option prints additionally the name of the category.  The.'
complete -c locale -s k --description 'option prints additionally the name of the keyword.'

