# lpr
# Autogenerated from man page /usr/share/man/man1/lpr.1.gz
complete -c lpr -s D --description 'enables some debugging output.'
complete -c lpr -s d --description 'specifies the device to which to send the output.'
complete -c lpr -s h --description 'does nothing and is accepted for compatibility only.'
complete -c lpr -s l --description 'disables CR/LF translation.'
complete -c lpr -s P --description 'an alias for -d.'

