# lyxclient
# Autogenerated from man page /usr/share/man/man1/lyxclient.1.gz
complete -c lyxclient -s p --description 'specify the pid of the running LyX process to which lyxclient should send com…'
complete -c lyxclient -s a --description 'specify explicitly which socket special file should be used.'
complete -c lyxclient -s t --description 'if LyX is configured to use a temporary directory other than /tmp, you must i…'
complete -c lyxclient -s c --description 'send a single command, print LyX information to standard output and exit.'
complete -c lyxclient -s g --description 'this is simply a wrapper for the command \'server-goto-file-row file line\'.'
complete -c lyxclient -s n --description 'when starting communication, lyxclient sends an idenfifier string to LyX.'
complete -c lyxclient -s h --description 'print the lyxclient version and summarize its usage.  ENVIRONMENT.'

