# mcp
# Autogenerated from man page /usr/share/man/man1/mcp.1.gz
complete -c mcp -s m --description 'move source file to target name.  Both must be on the same device.'
complete -c mcp -s x --description 'same as -m, except cross-device moves are done by copying, then deleting sour…'
complete -c mcp -s r --description 'rename source file or directory to target name.'
complete -c mcp -s c --description 'copy source file to target name.'
complete -c mcp -s o --description 'overwrite target name with source file.'
complete -c mcp -s a --description 'append contents of source file to target name.'
complete -c mcp -s z --description 'same as -a, but if the target file exists, and its last character is a ^Z, an…'
complete -c mcp -s l --description 'link target name to source file.'
complete -c mcp -s s --description 'same as -l, but use symbolic links instead of hard links.'
complete -c mcp -s g -s t --description 'The former will resolve all difficulties by avoiding the erroneous actions; t…'

