# minidumper
# Autogenerated from man page /usr/share/man/man1/minidumper.1.gz
complete -c minidumper -s t -l type --description '.'
complete -c minidumper -s n -l nokill --description '.'
complete -c minidumper -s d -l verbose --description '.'
complete -c minidumper -s h -l help --description '.'
complete -c minidumper -s q -l quiet --description '.'
complete -c minidumper -s V -l version --description '   DESCRIPTION.'

