# mkfs
# Autogenerated from man page /usr/share/man/man8/mkfs.minix.8.gz
complete -c mkfs -s 1 --description 'Make a Minix version 1 filesystem.'
complete -c mkfs -s 2 --description 'Make a Minix version 2 filesystem.'
complete -c mkfs -s 3 --description 'Make a Minix version 3 filesystem.  EXIT CODES The exit code returned by mkfs.'

