# mkgroup
# Autogenerated from man page /usr/share/man/man1/mkgroup.1.gz
complete -c mkgroup -s d --description 'and.'
complete -c mkgroup -o l/-L --description 'options allow you to specify where the information comes from, some domain, o…'
complete -c mkgroup -s L --description 'option, but you dont like the default domain/group separator from /etc/nsswit…'
complete -c mkgroup -s S --description 'option, for instance:.'
complete -c mkgroup -o 'c.' --description '.'
complete -c mkgroup -s o --description 'option allows for (unlikely) special cases with multiple machines where the G…'
complete -c mkgroup -s g --description 'option only prints the information for one group.  The.'
complete -c mkgroup -s U --description 'option allows you to enumerate the standard UNIX groups on a Samba machine.'
complete -c mkgroup -s l --description 'or.'

