# mkpasswd
# Autogenerated from man page /usr/share/man/man1/mkpasswd.1.gz
complete -c mkpasswd -s d --description 'and.'
complete -c mkpasswd -o l/-L --description 'options allow you to specify where the information comes from, some domain, o…'
complete -c mkpasswd -s L --description 'option, but you dont like the default domain/group separator from /etc/nsswit…'
complete -c mkpasswd -s S --description 'option, analog to mkgroup.'
complete -c mkpasswd -o 'c.' --description '.'
complete -c mkpasswd -s o --description 'option allows for special cases (such as multiple domains) where the UIDs mig…'
complete -c mkpasswd -s p --description 'option causes mkpasswd to use the specified prefix instead of the account hom…'
complete -c mkpasswd -s u --description 'option creates just an entry for the specified user.  The.'
complete -c mkpasswd -s U --description 'option allows you to enumerate the standard UNIX users on a Samba machine.'
complete -c mkpasswd -s l --description 'or.'

