# mount
# Autogenerated from man page /usr/share/man/man1/mount.1.gz
complete -c mount -s f --description '(force) option causes the old mount to be silently replaced with the new one,…'
complete -c mount -s o --description 'option is the method via which various options about the mount point may be r…'
complete -c mount -o a/--all --description 'option, or by specifing the posix path alone on the command line.'
complete -c mount -s m --description 'option causes the mount utility to output the current mount table in a series…'
complete -c mount -s p --description 'option.  Using the.'
complete -c mount -l options --description 'flag with.'
complete -c mount -l change-cygdrive-prefix --description 'makes all new automounted filesystems default to this set of options.'

