# pdiff
# Autogenerated from man page /usr/share/man/man1/pdiff.1.gz
complete -c pdiff -s h -l help --description 'display this help and exit.'
complete -c pdiff -s v -l version --description 'display version information and exit.'
complete -c pdiff -s q -l quiet --description 'don\'t print informational messages.'
complete -c pdiff -s l -l lines --description 'search for line differences (`diff\').'
complete -c pdiff -s w -l words --description 'search for word differences (`wdiff\').'
complete -c pdiff -s o -l output --description 'save the output in FILE .'

