# ping
# Autogenerated from man page /usr/share/man/man1/ping.1.gz
complete -c ping -s v --description 'Verbose output.'
complete -c ping -s q --description 'Quiet output.   Nothing is displayed except the summary line on termination.'
complete -c ping -s f --description 'Flood ping.'
complete -c ping -s r --description 'Bypass the normal routing tables and send directly to a host on an attached n…'
complete -c ping -s d --description 'Set the SO_DEBUG option on the socket being used.'

