# png2bmp
# Autogenerated from man page /usr/share/man/man1/png2bmp.1.gz
complete -c png2bmp -s a --description 'Preserve alpha channel (save in 32bit \\s-1ARGB\\s0 \\s-1BMP\\s0 format).'
complete -c png2bmp -s b --description 'Preserve alpha channel (save in 32bit Bitfield \\s-1BMP\\s0 format).'
complete -c png2bmp -s e --description 'Delete input files after successful conversion.'
complete -c png2bmp -s d --description 'Output files into dir.'
complete -c png2bmp -s h --description 'Display short help.'
complete -c png2bmp -s l --description 'Log errors to \\f(CW\\*(C`. /p2berror. log\\*(C\' file.'
complete -c png2bmp -s o --description 'Specify name for output \\s-1FILE\\s0.'
complete -c png2bmp -s r --description 'Convert transparent color to alpha channel (use with -a or -b).'
complete -c png2bmp -s t --description 'Set the timestamp of input file on output file.'
complete -c png2bmp -s q --description 'Quiet mode.'

