# prockill
# Autogenerated from man page /usr/share/man/man1/prockill.1.gz
complete -c prockill -o '<signal>' --description 'TQ  -s <signal> . TQ  --signal <signal> Specify the  signal to be sent.'
complete -c prockill -s l -l list --description 'List signal names.'
complete -c prockill -s L -l table --description 'List signal names in a nice table.'
complete -c prockill -s 9 -o SIGKILL --description 'or.'
complete -c prockill -o KILL --description 'Negative PID values may be used to choose whole process groups; see the PGID …'
complete -c prockill -s 1 --description 'is special; it indicates all processes except the kill process itself and ini…'
complete -c prockill -s s --description '.'
complete -c prockill -l signal --description 'Specify the signal to be sent.'

