# psmandup
# Autogenerated from man page /usr/share/man/man1/psmandup.1.gz
complete -c psmandup -s h -l help --description 'display this help and exit.'
complete -c psmandup -s v -l version --description 'display version information and exit.'
complete -c psmandup -s q -l quiet --description 'don\'t print informational messages.'
complete -c psmandup -s o -l output --description 'save result in FILE.   If FILE is `-\', send to stdout.'
complete -c psmandup -s n -l no-fix --description 'don\'t call fixps to fix PS problems in FILE.'
complete -c psmandup -s f -l front --description 'output only the front pages (recto) on the regular tray.'
complete -c psmandup -s b -l back --description 'output only the back pages (verso) on the manual feed tray.'

