# psset
# Autogenerated from man page /usr/share/man/man1/psset.1.gz
complete -c psset -s h -l help --description 'display this help and exit.'
complete -c psset -s v -l version --description 'display version information and exit.'
complete -c psset -s q -l quiet --description 'don\'t print informational messages.'
complete -c psset -s o -l output --description 'save result in FILE.   If FILE is `-\', send to stdout.'
complete -c psset -s n -l no-fix --description 'don\'t run `fixps\' to fix PS problems in FILE.'
complete -c psset -s S -l setpagedevice --description 'pass a page device definition to output.  Multiple values accumulate.'
complete -c psset -s a -l at --description 'insert the page device definitions at PAGE.'
complete -c psset -s m -l manualfeed --description 'alias for -SManualFeed:true.'
complete -c psset -s s -l simplex --description 'alias for -SDuplex:false.'
complete -c psset -s d -l duplex --description 'alias for -SDuplex:true -STumble:false corresponds to Duplex, binding along t…'
complete -c psset -s t -l tumble --description 'alias for -SDuplex:true -STumble:true corresponds to Duplex, binding along th…'

