# pstotext
# Autogenerated from man page /usr/share/man/man1/pstotext.1.gz
complete -c pstotext -o 'Ic:\\gs;c:\\gs\\fonts' --description '.'
complete -c pstotext -o 'landscapeOther}' --description 'space.'

