# rgb2ycbcr
# Autogenerated from man page /usr/share/man/man1/rgb2ycbcr.1.gz
complete -c rgb2ycbcr -s c --description 'Specify a compression scheme to use when writing image data:  "-c none" for n…'
complete -c rgb2ycbcr -s h --description 'Set the horizontal sampling dimension to one of: 1, 2 (default), or 4.'
complete -c rgb2ycbcr -s r --description 'Write data with a specified number of rows per strip; by default the number o…'
complete -c rgb2ycbcr -s v --description 'options.  Output data are compressed with the.'

