# run2
# Autogenerated from man page /usr/share/man/man1/run2.1.gz
complete -c run2 -s h -l help --description 'print this help message and exit.'
complete -c run2 -s v -l version --description 'print version information and exit.'
complete -c run2 -s d -l display --description 'use STRING instead of $DISPLAY.'
complete -c run2 -s x -l xlibname --description 'use exactly STRING instead of fuzzy cygX11-n. dll search.'
complete -c run2 -s t -l timeout --description 'allow FLOAT seconds to connect with Xserver defaults to 0. 5, use 0.'
complete -c run2 -l force-gdi --description 'unconditionally launch GDI configuration.'
complete -c run2 -l force-x11 --description 'unconditionally launch X11 configuration.'
complete -c run2 -s w -l wait --description 'wait for the target app to complete before returning.'
complete -c run2 -l nogui --description 'disable informational popups.'
complete -c run2 -l notty --description 'disable stderr messages.'
complete -c run2 -l silent --description 'suppress all but fatal error messages (default).'
complete -c run2 -l no-silent --description 'allow (fatal and non-fatal) error messages.'
complete -c run2 -l no-verbose --description 'same as --no-silent.'
complete -c run2 -l verbose --description 'allow error, warning, and info messages.'
complete -c run2 -l debug --description 'turn on debugging messages, as well as those enabled by --verbose.'
complete -c run2 -l 'verbose.' --description 'higher than 1 enable increasing details.'

