# setfacl
# Autogenerated from man page /usr/share/man/man1/setfacl.1.gz
complete -c setfacl -s f --description 'the section called “POSIX accounts, permission, and security” in the Cygwin U…'
complete -c setfacl -s b -l remove-all --description 'Remove all extended ACL entries.'
complete -c setfacl -s k -l remove-default --description 'option to delete all non-standard POSIX permissions.'
complete -c setfacl -s x -l delete --description 'Delete one or more specified entries from the files ACL.'
complete -c setfacl -l file --description 'Take the Acl_entries from ACL_FILE one per line.'
complete -c setfacl -s m -l modify --description 'Add or modify one or more specified ACL entries.'
complete -c setfacl -s n -l no-mask --description 'Valid in conjunction with -m.  Do not recalculate the effective rights mask.'
complete -c setfacl -l mask --description 'Valid in conjunction with -m.'
complete -c setfacl -s s -l set --description 'Like.'

