# sgi2tiff
# Autogenerated from man page /usr/share/man/man1/sgi2tiff.1.gz
complete -c sgi2tiff -s c --description 'Specify a compression scheme to use when writing image data:  "-c none" for n…'
complete -c sgi2tiff -s p --description 'Explicitly select the planar configuration used in organizing data samples in…'
complete -c sgi2tiff -s r --description 'Write data with a specified number of rows per strip; by default the number o…'

