# ssp
# Autogenerated from man page /usr/share/man/man1/ssp.1.gz
complete -c ssp -s d --description 'option to ssp to default to *disabling* profiling.'
complete -c ssp -s v --description '.'
complete -c ssp -s t --description 'and.'
complete -c ssp -s c --description '.'
complete -c ssp -s s --description '.'
complete -c ssp -s l --description '.'

