# strace
# Autogenerated from man page /usr/share/man/man1/strace.1.gz
complete -c strace -s o --description 'option.  With the.'
complete -c strace -s w --description 'option, you can start an strace session in a new window, for example: $ strac…'

