# symlinks
# Autogenerated from man page /usr/share/man/man1/symlinks.1.gz
complete -c symlinks -s c --description 'convert absolute links (within the same filesystem) to relative links.'
complete -c symlinks -s d --description 'causes  dangling links to be removed.'
complete -c symlinks -s o --description 'fix links on other filesystems encountered while recursing.'
complete -c symlinks -s r --description 'recursively operate on subdirectories within the same filesystem.'
complete -c symlinks -s s --description 'causes  lengthy links to be detected.'
complete -c symlinks -s t --description 'is used to test for what  symlinks would do if  -c were specified, but withou…'
complete -c symlinks -s v --description 'show all symbolic links.   By default,  relative links are not shown unless .'

