# tex2lyx
# Autogenerated from man page /usr/share/man/man1/tex2lyx.1.gz
complete -c tex2lyx -s c --description 'Class.'
complete -c tex2lyx -s m --description 'Module.  Load the given modules.'
complete -c tex2lyx -s f --description 'Force.  tex2lyx will not run if the .'
complete -c tex2lyx -s e --description 'Specify the default encoding using the LaTeX name as defined in the encodings…'
complete -c tex2lyx -o fixedenc --description 'Specify the encoding using the LaTeX name as defined in the encodings file.'
complete -c tex2lyx -s n --description 'Noweb.  Translate a noweb (aka literate programming) file.'
complete -c tex2lyx -o skipchildren --description 'Do not translate child documents included via \\f(CWinclude and \\f(CWinput.'
complete -c tex2lyx -s s --description 'Syntax files.'
complete -c tex2lyx -o sysdir --description 'Specify a system directory.  Normally, you shouldn\'t need this.'
complete -c tex2lyx -o userdir --description 'Specify a user directory.  Normally, you shouldn\'t need this.'
complete -c tex2lyx -o roundtrip --description 'Call LyX to re-export the created output file to LaTeX.'
complete -c tex2lyx -o copyfiles --description 'Copy all included files tex2lyx is aware of to the output directory if the ou…'
complete -c tex2lyx -o help --description 'Help.  Print out usage information and quit.'

