# texi2dvi4a2ps
# Autogenerated from man page /usr/share/man/man1/texi2dvi4a2ps.1.gz
complete -c texi2dvi4a2ps -s b -l batch --description 'no interaction.'
complete -c texi2dvi4a2ps -s c -l clean --description 'remove all auxiliary files.'
complete -c texi2dvi4a2ps -s D -l debug --description 'turn on shell debugging (set -x).'
complete -c texi2dvi4a2ps -s h -l help --description 'display this help and exit successfully.'
complete -c texi2dvi4a2ps -s o -l output --description 'leave output in OFILE (implies --clean); Only one input FILE may be specified…'
complete -c texi2dvi4a2ps -s q -l quiet --description 'no output unless errors (implies --batch).'
complete -c texi2dvi4a2ps -s s -l silent --description 'same as --quiet.'
complete -c texi2dvi4a2ps -s v -l version --description 'display version information and exit successfully.'
complete -c texi2dvi4a2ps -s V -l verbose --description 'report on what is done . SS "TeX tuning:".'
complete -c texi2dvi4a2ps -s @ --description 'use @input instead of input; for preloaded Texinfo.'
complete -c texi2dvi4a2ps -s e -l expand --description 'force macro expansion using makeinfo.'
complete -c texi2dvi4a2ps -s I --description 'search DIR for Texinfo files.'
complete -c texi2dvi4a2ps -s l -l language --description 'specify the LANG of FILE (LaTeX or Texinfo).'
complete -c texi2dvi4a2ps -s p -l pdf --description 'use pdftex or pdflatex for processing.'
complete -c texi2dvi4a2ps -s t -l texinfo --description 'insert CMD after @setfilename in copy of input file multiple values accumulat…'

