# tiffsv
# Autogenerated from man page /usr/share/man/man1/tiffsv.1.gz
complete -c tiffsv -s b --description 'Save the image as a greyscale image as if it were processed by  R tiff2bw (1).'
complete -c tiffsv -s c --description 'Specify the compression to use for data written to the output file:  none  fo…'
complete -c tiffsv -s p --description 'Specify the planar configuration to use in writing image data.'
complete -c tiffsv -s r --description 'Specify the number of rows (scanlines) in each strip of data written to the o…'

