# tkpod
# Autogenerated from man page /usr/share/man/man1/tkpod.1.gz
complete -c tkpod -o tree --description 'When specified, \\f(CW\\*(C`tkpod\\*(C\' will show a tree window with all availab…'
complete -c tkpod -o tk --description 'Useful for perl/Tk documentation.'
complete -c tkpod -s s -o server --description 'Start \\f(CW\\*(C`tkpod\\*(C\' in server mode.'
complete -c tkpod -s d -o debug --description 'Turn debugging on.'
complete -c tkpod -o Mblib --description 'Add the \\f(CW\\*(C`blib\\*(C\' directories under the current directory to the Po…'
complete -c tkpod -s I --description 'Add another directory to the Pod search path.'
complete -c tkpod -s f --description 'Show documentation for function.'
complete -c tkpod -s q --description 'Show the \\s-1FAQ\\s0 entry matching FAQRegex.'

