# txt2regex
# Autogenerated from man page /usr/share/man/man1/txt2regex.1.gz
complete -c txt2regex -l all --description 'works with all registered programs.'
complete -c txt2regex -l help --description 'prints the help message and quit.'
complete -c txt2regex -l history --description 'prints to STDOUT a regex from a history data.'
complete -c txt2regex -l make --description 'prints a ready regex for a common pattern.'
complete -c txt2regex -l nocolor --description 'self-explanatory.'
complete -c txt2regex -l prog --description 'choose which programs to use (separated by commas).'
complete -c txt2regex -l showinfo --description 'prints regex info about the program.'
complete -c txt2regex -l showmeta --description 'prints a complete metachar table for all programs.'
complete -c txt2regex -l version --description 'prints the program version and quit.'
complete -c txt2regex -l whitebg --description 'colors adjusted to white background terminals By default, all options are tur…'

