# untex
# Autogenerated from man page /usr/share/man/man1/untex.1.gz
complete -c untex -s o --description 'remove options to LaTeX commands, i.  e.'
complete -c untex -s i --description 'process "\\\\include{file}" and "\\\\input{file}" and "\\\\input file" commands.'
complete -c untex -s m --description '(try to) remove all math code.'
complete -c untex -s u --description 'replace all \\\\"a (etc. ) with ibm (CP850) characters.'
complete -c untex -o uiso --description 'replace all \\\\"a (etc. ) with ISO characters.'
complete -c untex -o uascii --description 'replace all \\\\"a (etc. ) with ascii characters.'
complete -c untex -s g --description 'replace all "a (etc. , from german. sty) with ibm (CP850) characters.'
complete -c untex -o giso --description 'replace all "a (etc. , from german. sty) with ISO characters.'
complete -c untex -o gascii --description 'replace all "a (etc. , from german. sty) with ascii characters.'
complete -c untex -s e --description 'remove environment names.'
complete -c untex -s a --description 'remove arguments of commands (not recommended).'
complete -c untex -o 'o.' --description '.'

