# uucpd
# Autogenerated from man page /usr/share/man/man8/uucpd.8.gz
complete -c uucpd -s '?' -l help --description 'give this help list.'
complete -c uucpd -l usage --description 'give a short usage message.'
complete -c uucpd -s V -l version --description 'print program version AUTHOR Written by many authors.'

