# Wand-config
# Autogenerated from man page /usr/share/man/man1/Wand-config.1.gz
complete -c Wand-config -l cflags --description 'Print the compiler flags that were used to compile   libWand .'
complete -c Wand-config -l cppflags --description 'Print the preprocessor flags that are needed to find the  Wand C include file…'
complete -c Wand-config -l exec-prefix --description 'Print the directory under which target specific binaries and executables are …'
complete -c Wand-config -l ldflags --description 'Print the linker flags that are needed to link with the  Wand library.'
complete -c Wand-config -l libs --description 'Print the linker flags that are needed to link a program with  libWand .'
complete -c Wand-config -l version --description 'Print the version of the Wand distribution to standard output.'

