# winln
# Autogenerated from man page /usr/share/man/man1/winln.1.gz
complete -c winln -s s -l symbolic --description 'Create a symbolic (as opposed to hard) link.'
complete -c winln -s v -l verbose --description 'Print to standard output the names of links created.'
complete -c winln -s f -l force --description 'Replace existing destination file.'
complete -c winln -s d -l directory --description 'Create a directory symbolic link.'
complete -c winln -s F -l file --description 'Create a file symbolic link.'
complete -c winln -s A -l auto --description 'Automatically determine the type of symbolic link to create.'
complete -c winln -s t -l target-directory --description 'Treat DIRECTORY as the directory in which to create links based on the remain…'
complete -c winln -s T -l no-target-directory --description 'Treat LINKNAME as a normal file always.'
complete -c winln -s h -l help --description 'Show brief help message.'
complete -c winln -l version --description 'Display version information.'
complete -c winln -s b -l backup --description '.'
complete -c winln -s i -l interactive --description '.'
complete -c winln -s L -l logical --description '.'
complete -c winln -s n -l no-dereference --description '.'
complete -c winln -s P -l physical --description '.'

