# xlsx2csv
# Autogenerated from man page /usr/share/man/man1/xlsx2csv.1.gz
complete -c xlsx2csv -s d -l delimiter --description 'Output csv columns delimiter.  Use \\*(L"tab\\*(R" or \\*(L"x09\\*(R" for tab.'
complete -c xlsx2csv -s f -l dateformat --description 'Set date/time format.  See strftime\\|(3) for %-format specifiers.'
complete -c xlsx2csv -s i -l ignoreempty --description 'Skip empty lines.'
complete -c xlsx2csv -s p -l sheetdelimiter --description 'Sheet delimiter used to separate sheets, pass "\\*(L" if you don\'t want delimi…'
complete -c xlsx2csv -s r -l recursive --description 'Convert recursively.'
complete -c xlsx2csv -s s -l sheet --description 'Sheet to convert (0 for all sheets).'
complete -c xlsx2csv -s h -l help --description 'Display short help and exit.'

