set nocp
filetype plugin indent on 
syntax on
set backspace=indent,eol,start
set hidden
set noswapfile

" let $RTP=split(&runtimepath, ',')[0]
" let $RC="$HOME/.vim/vimrc"

set number
set relativenumber

set laststatus=2
set t_Co=256
set nohlsearch


" status bar settup-01
" added manually 2201203
" source /home/gregor.redelonghi/.vim/vim-status-1.vim
"

" status bar settup-02
" added from: https://github.com/itchyny/lightline.vim
" git clone https://github.com/itchyny/lightline.vim ~/.vim/pack/plugins/start/lightline
"
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ }
