set nocp
filetype plugin indent on 
syntax on
set backspace=indent,eol,start
set hidden
set noswapfile

" let $RTP=split(&runtimepath, ',')[0]
" let $RC="$HOME/.vim/vimrc"

set number
set relativenumber

set laststatus=2
set t_Co=256
set nohlsearch

source /home/gregor.redelonghi/.vim/vim-status-1.vim
